[package]
name = "aarch64-bare-metal"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
spin = "0.9"

[profile.release]
codegen-units = 1
lto = true
debug = true
opt-level = "s"
panic = "abort"
